# Generated by Django 5.1.15 on 2026-03-08 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('refunds', '0002_refundrequest_transfer_reversal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='refundrequest',
            options={'permissions': (('can_trigger_refunds', 'Can trigger refunds'),)},
        ),
    ]
