# Generated by Django 5.1.15 on 2026-02-14 13:41

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SellerBalanceEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "amount_cents",
                    models.IntegerField(
                        help_text="Signed cents. Positive = owed to seller, negative = seller owes platform."
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("sale", "Sale (order paid)"),
                            ("payout", "Payout"),
                            ("refund", "Refund"),
                            ("chargeback", "Chargeback"),
                            ("adjustment", "Manual adjustment"),
                        ],
                        max_length=32,
                    ),
                ),
                ("note", models.TextField(blank=True, default="")),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="seller_balance_entries",
                        to="orders.order",
                    ),
                ),
                (
                    "order_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="seller_balance_entries",
                        to="orders.orderitem",
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="balance_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["seller", "-created_at"],
                        name="payments_se_seller__2b9460_idx",
                    ),
                    models.Index(
                        fields=["reason", "-created_at"],
                        name="payments_se_reason_8966a2_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("seller", "order", "reason"),
                        name="uniq_seller_order_reason",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SellerFeeWaiver",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("starts_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("ends_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fee_waiver",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["ends_at"], name="payments_se_ends_at_6b4860_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SellerStripeAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stripe_account_id",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=255
                    ),
                ),
                ("details_submitted", models.BooleanField(default=False)),
                ("charges_enabled", models.BooleanField(default=False)),
                ("payouts_enabled", models.BooleanField(default=False)),
                ("onboarding_started_at", models.DateTimeField(blank=True, null=True)),
                (
                    "onboarding_completed_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stripe_connect",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["stripe_account_id"],
                        name="payments_se_stripe__722205_idx",
                    ),
                    models.Index(
                        fields=[
                            "details_submitted",
                            "charges_enabled",
                            "payouts_enabled",
                        ],
                        name="payments_se_details_2e0821_idx",
                    ),
                ],
            },
        ),
    ]
