# Generated by ChatGPT on 2026-03-11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0008_alter_order_platform_fee_cents_snapshot"),
        ("payments", "0002_sellerfeeplan"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SellerFeeInvoice",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("amount_cents", models.PositiveIntegerField(default=0)),
                ("status", models.CharField(choices=[("open", "Open"), ("paid", "Paid"), ("void", "Voided")], db_index=True, default="open", max_length=16)),
                ("payment_method_snapshot", models.CharField(blank=True, default="", max_length=20)),
                ("stripe_session_id", models.CharField(blank=True, db_index=True, default="", max_length=255)),
                ("stripe_payment_intent_id", models.CharField(blank=True, default="", max_length=255)),
                ("paid_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("note", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("order", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="seller_fee_invoices", to="orders.order")),
                ("seller", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="fee_invoices", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.AddIndex(
            model_name="sellerfeeinvoice",
            index=models.Index(fields=["seller", "status", "-created_at"], name="payments_sel_seller__180d7f_idx"),
        ),
        migrations.AddIndex(
            model_name="sellerfeeinvoice",
            index=models.Index(fields=["order", "status"], name="payments_sel_order_i_b1fd98_idx"),
        ),
        migrations.AddConstraint(
            model_name="sellerfeeinvoice",
            constraint=models.UniqueConstraint(fields=("seller", "order"), name="uniq_seller_fee_invoice_per_order"),
        ),
    ]
