# Generated by Django 5.1.15 on 2026-03-11 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_sellerfeeinvoice'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='sellerfeeinvoice',
            new_name='payments_se_seller__605481_idx',
            old_name='payments_sel_seller__180d7f_idx',
        ),
        migrations.RenameIndex(
            model_name='sellerfeeinvoice',
            new_name='payments_se_order_i_893e2d_idx',
            old_name='payments_sel_order_i_b1fd98_idx',
        ),
    ]
