# Generated by Django 5.1.15 on 2026-03-13 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_sellerpaypalaccount'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='sellerpaypalaccount',
            new_name='payments_se_paypal__cde237_idx',
            old_name='payments_se_paypal__d6d212_idx',
        ),
        migrations.RenameIndex(
            model_name='sellerpaypalaccount',
            new_name='payments_se_payment_699e50_idx',
            old_name='payments_se_payment_0f2626_idx',
        ),
    ]
