# Generated by Django 5.1.15 on 2026-02-14 13:41

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("qa", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AdvertisementBanner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("image", models.ImageField(upload_to="ad_banners/")),
                ("link_url", models.URLField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("start_date", models.DateTimeField(default=django.utils.timezone.now)),
                ("end_date", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SiteConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "promo_banner_enabled",
                    models.BooleanField(
                        default=False,
                        help_text="If enabled, show a promo banner above the navbar sitewide.",
                    ),
                ),
                (
                    "promo_banner_text",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Text shown in the promo banner. Keep it short.",
                        max_length=240,
                    ),
                ),
                (
                    "home_banner_enabled",
                    models.BooleanField(
                        default=False,
                        help_text="If enabled, show a banner on the home page (only).",
                    ),
                ),
                (
                    "home_banner_text",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Text shown in the home page banner. Keep it short.",
                        max_length=240,
                    ),
                ),
                (
                    "seller_fee_waiver_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="If enabled, new sellers receive a temporary 0% marketplace cut.",
                    ),
                ),
                (
                    "seller_fee_waiver_days",
                    models.PositiveIntegerField(
                        default=30,
                        help_text="Length of new-seller fee waiver window in days.",
                    ),
                ),
                (
                    "affiliate_links_enabled",
                    models.BooleanField(
                        default=False,
                        help_text="If enabled, show affiliate product links (e.g., Amazon Associates) in the store sidebar.",
                    ),
                ),
                (
                    "affiliate_links_title",
                    models.CharField(
                        blank=True,
                        default="Recommended Products",
                        help_text="Sidebar section heading for affiliate links.",
                        max_length=80,
                    ),
                ),
                (
                    "affiliate_disclosure_text",
                    models.CharField(
                        blank=True,
                        default="As an Amazon Associate I earn from qualifying purchases.",
                        help_text="Short disclosure shown under the affiliate links (recommended).",
                        max_length=240,
                    ),
                ),
                (
                    "affiliate_links",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of links shown in the sidebar. Example item: {'label':'SUNLU PLA 1kg','url':'https://...','note':'Budget PLA+'} (label+url required; note optional).",
                    ),
                ),
                (
                    "home_hero_title",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Home page hero headline (left side).",
                        max_length=120,
                    ),
                ),
                (
                    "home_hero_subtitle",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Home page hero paragraph (left side).",
                    ),
                ),
                (
                    "marketplace_sales_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("8.00"),
                        help_text="Percent of sales withheld by the marketplace (e.g., 15.00 = 15%).",
                        max_digits=6,
                    ),
                ),
                (
                    "platform_fee_cents",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Optional fixed fee in cents added to each order (0 disables).",
                    ),
                ),
                (
                    "default_currency",
                    models.CharField(
                        default="usd",
                        help_text="Default currency (Stripe-style), e.g. 'usd'.",
                        max_length=8,
                    ),
                ),
                (
                    "allowed_shipping_countries",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of allowed country codes for shipping (e.g. ['US']).",
                    ),
                ),
                (
                    "plausible_shared_url",
                    models.URLField(
                        blank=True,
                        default="",
                        help_text="Plausible shared dashboard URL (read-only). Example: https://plausible.io/share/<site>?auth=...",
                    ),
                ),
                (
                    "google_analytics_dashboard_url",
                    models.URLField(
                        blank=True,
                        default="",
                        help_text="Google Analytics dashboard URL (for quick access from the admin dashboard).",
                    ),
                ),
                (
                    "analytics_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="If enabled, record lightweight pageview analytics for the admin dashboard.",
                    ),
                ),
                (
                    "analytics_retention_days",
                    models.PositiveIntegerField(
                        default=90,
                        help_text="How many days of analytics events to retain (pruned by management command).",
                    ),
                ),
                (
                    "analytics_exclude_staff",
                    models.BooleanField(
                        default=True,
                        help_text="If enabled, exclude staff/admin browsing from native analytics.",
                    ),
                ),
                (
                    "analytics_exclude_admin_paths",
                    models.BooleanField(
                        default=True,
                        help_text="If enabled, exclude /admin/ and /dashboard/ paths from native analytics.",
                    ),
                ),
                (
                    "analytics_primary_host",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Optional: restrict native analytics reports to this host (e.g. localmarketne.com). Leave blank for all hosts.",
                        max_length=255,
                    ),
                ),
                (
                    "analytics_primary_environment",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Optional: restrict native analytics reports to this environment (e.g. production). Leave blank for all.",
                        max_length=32,
                    ),
                ),
                (
                    "theme_default_mode",
                    models.CharField(
                        choices=[("light", "Light"), ("dark", "Dark")],
                        default="light",
                        help_text="Default mode for new visitors (users may toggle).",
                        max_length=10,
                    ),
                ),
                (
                    "theme_primary",
                    models.CharField(
                        default="#F97316",
                        help_text="Primary action color (hex).",
                        max_length=20,
                    ),
                ),
                (
                    "theme_accent",
                    models.CharField(
                        default="#F97316",
                        help_text="Accent color (hex).",
                        max_length=20,
                    ),
                ),
                (
                    "theme_success",
                    models.CharField(
                        default="#16A34A",
                        help_text="Success color (hex).",
                        max_length=20,
                    ),
                ),
                (
                    "theme_danger",
                    models.CharField(
                        default="#DC2626",
                        help_text="Danger color (hex).",
                        max_length=20,
                    ),
                ),
                (
                    "theme_light_bg",
                    models.CharField(
                        default="#F9FAFB",
                        help_text="Light mode background (hex).",
                        max_length=20,
                    ),
                ),
                (
                    "theme_light_surface",
                    models.CharField(
                        default="#FFFFFF",
                        help_text="Light mode surface/card background (hex).",
                        max_length=20,
                    ),
                ),
                (
                    "theme_light_text",
                    models.CharField(
                        default="#111827",
                        help_text="Light mode text color (hex).",
                        max_length=20,
                    ),
                ),
                (
                    "theme_light_text_muted",
                    models.CharField(
                        default="#6B7280",
                        help_text="Light mode muted text (hex).",
                        max_length=20,
                    ),
                ),
                (
                    "theme_light_border",
                    models.CharField(
                        default="#E5E7EB",
                        help_text="Light mode border color (hex).",
                        max_length=20,
                    ),
                ),
                (
                    "theme_dark_bg",
                    models.CharField(
                        default="#0B1220",
                        help_text="Dark mode background (hex).",
                        max_length=20,
                    ),
                ),
                (
                    "theme_dark_surface",
                    models.CharField(
                        default="#111B2E",
                        help_text="Dark mode surface/card background (hex).",
                        max_length=20,
                    ),
                ),
                (
                    "theme_dark_text",
                    models.CharField(
                        default="#EAF0FF",
                        help_text="Dark mode text color (hex).",
                        max_length=20,
                    ),
                ),
                (
                    "theme_dark_text_muted",
                    models.CharField(
                        default="#9FB0D0",
                        help_text="Dark mode muted text (hex).",
                        max_length=20,
                    ),
                ),
                (
                    "theme_dark_border",
                    models.CharField(
                        default="#22304D",
                        help_text="Dark mode border color (hex).",
                        max_length=20,
                    ),
                ),
                (
                    "facebook_url",
                    models.URLField(
                        blank=True,
                        default="",
                        help_text="Optional Facebook page URL for footer icon.",
                    ),
                ),
                (
                    "instagram_url",
                    models.URLField(
                        blank=True,
                        default="",
                        help_text="Optional Instagram profile URL for footer icon.",
                    ),
                ),
                (
                    "tiktok_url",
                    models.URLField(
                        blank=True,
                        default="",
                        help_text="Optional TikTok profile URL for footer icon.",
                    ),
                ),
                (
                    "youtube_url",
                    models.URLField(
                        blank=True,
                        default="",
                        help_text="Optional YouTube channel URL for footer icon.",
                    ),
                ),
                (
                    "x_url",
                    models.URLField(
                        blank=True,
                        default="",
                        help_text="Optional X (Twitter) profile URL for footer icon.",
                    ),
                ),
                (
                    "linkedin_url",
                    models.URLField(
                        blank=True,
                        default="",
                        help_text="Optional LinkedIn page URL for footer icon.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("appointment_reminders_enabled", models.BooleanField(default=True)),
                (
                    "appointment_reminder_hours_before",
                    models.PositiveIntegerField(default=24),
                ),
            ],
            options={
                "verbose_name": "Site Config",
                "verbose_name_plural": "Site Config",
            },
        ),
        migrations.CreateModel(
            name="SiteEmailTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Template identifier (e.g. 'staff_announcement')",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "subject",
                    models.CharField(help_text="Email subject line", max_length=200),
                ),
                (
                    "body",
                    models.TextField(
                        help_text="Email body. You can use {{ user }}, {{ site_name }}, etc."
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "site_config",
                    models.ForeignKey(
                        blank=True,
                        help_text="Site config this template belongs to.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_templates",
                        to="core.siteconfig",
                    ),
                ),
            ],
            options={
                "verbose_name": "Site Email Template",
                "verbose_name_plural": "Site Email Templates",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="StaffActionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("qa_report_resolved", "Q&A report resolved"),
                            ("qa_message_removed", "Q&A message removed"),
                            ("user_suspended", "User suspended"),
                            ("user_unsuspended", "User unsuspended"),
                        ],
                        db_index=True,
                        max_length=40,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("appointment_reminders_enabled", models.BooleanField(default=True)),
                (
                    "appointment_reminder_hours_before",
                    models.PositiveIntegerField(default=24),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        help_text="Staff user who performed the action.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="staff_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "qa_message",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="staff_actions",
                        to="qa.productquestionmessage",
                    ),
                ),
                (
                    "qa_report",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="staff_actions",
                        to="qa.productquestionreport",
                    ),
                ),
                (
                    "target_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="staff_actions_targeted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["action", "-created_at"],
                        name="core_staffa_action_7ad111_idx",
                    ),
                    models.Index(
                        fields=["-created_at"], name="core_staffa_created_11c74b_idx"
                    ),
                ],
            },
        ),
    ]
