# Generated by ChatGPT on 2026-02-14
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfig",
            name="require_age_18",
            field=models.BooleanField(
                default=True,
                help_text="If enabled, users must confirm they are 18+ to place orders.",
            ),
        ),
        migrations.AddField(
            model_name="siteconfig",
            name="age_gate_text",
            field=models.CharField(
                max_length=240,
                blank=True,
                default="You must be 18+ to use this marketplace.",
                help_text="Shown when a user must confirm age to proceed.",
            ),
        ),
    ]
