# Generated by ChatGPT (Pack AE) on 2026-02-15
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_siteconfig_age_gate"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfig",
            name="site_announcement_enabled",
            field=models.BooleanField(
                default=False,
                help_text="If enabled, show a site-wide announcement bar below the promo banner.",
            ),
        ),
        migrations.AddField(
            model_name="siteconfig",
            name="site_announcement_text",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Announcement text shown sitewide. Keep it short.",
                max_length=240,
            ),
        ),
        migrations.AddField(
            model_name="siteconfig",
            name="maintenance_mode_enabled",
            field=models.BooleanField(
                default=False,
                help_text="If enabled, non-staff visitors see a maintenance page (OPS/Staff can still access the site).",
            ),
        ),
        migrations.AddField(
            model_name="siteconfig",
            name="maintenance_mode_message",
            field=models.CharField(
                blank=True,
                default="We’re performing maintenance. Please check back soon.",
                help_text="Message shown on the maintenance page.",
                max_length=240,
            ),
        ),
        migrations.AddField(
            model_name="siteconfig",
            name="featured_seller_usernames",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of seller usernames to feature on the home page (optional).",
            ),
        ),
        migrations.AddField(
            model_name="siteconfig",
            name="featured_category_ids",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of category IDs to feature on the home page (optional).",
            ),
        ),
    ]
