# Generated by Django 5.1.15 on 2026-02-12 00:17

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_siteconfig_age_gate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfig',
            name='marketplace_sales_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('15.00'), help_text='Percent of sales withheld by the marketplace (e.g., 15.00 = 15%).', max_digits=6),
        ),
    ]
