# Generated by Django 5.1.15 on 2026-02-15 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_siteconfig_store_ops'),
        ('core', '0020_alter_siteconfig_marketplace_sales_percent'),
    ]

    operations = [
    ]
