# Generated by ChatGPT on 2026-02-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_merge_20260215_1454"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfig",
            name="seo_default_description",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Default meta description used sitewide (can be overridden per page).",
                max_length=240,
            ),
        ),
        migrations.AddField(
            model_name="siteconfig",
            name="seo_default_og_image_url",
            field=models.URLField(
                blank=True,
                default="",
                help_text="Absolute URL for the default OG/Twitter sharing image. Leave blank to use the bundled default.",
            ),
        ),
        migrations.AddField(
            model_name="siteconfig",
            name="seo_twitter_handle",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Optional Twitter/X handle (without @) for twitter:site.",
                max_length=32,
            ),
        ),
    ]
