# Generated by Django 5.1.15 on 2026-02-16 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_siteconfig_seller_onboarding_policy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfig',
            name='age_gate_text',
            field=models.CharField(blank=True, default='You must be 18+ to use this marketplace.', help_text='(Deprecated) Legacy buyer age gate message.', max_length=240),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='require_age_18',
            field=models.BooleanField(default=True, help_text='(Deprecated) Previously gated buyers. Use seller age confirmation for seller onboarding.'),
        ),
    ]
