# Generated by ChatGPT on 2026-02-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0025_waitlistentry"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfig",
            name="waitlist_enabled",
            field=models.BooleanField(
                default=True,
                help_text="If enabled, the public waitlist signup page is available.",
            ),
        ),
        migrations.AddField(
            model_name="siteconfig",
            name="waitlist_send_confirmation",
            field=models.BooleanField(
                default=False,
                help_text="If enabled, send a confirmation email to new waitlist signups.",
            ),
        ),
        migrations.AddField(
            model_name="siteconfig",
            name="waitlist_admin_notify_enabled",
            field=models.BooleanField(
                default=False,
                help_text="If enabled, notify the admin address when a new waitlist entry is created.",
            ),
        ),
        migrations.AddField(
            model_name="siteconfig",
            name="waitlist_admin_email",
            field=models.EmailField(
                blank=True,
                default="",
                help_text="Admin email to notify for new waitlist signups (used only if admin notify is enabled).",
                max_length=254,
            ),
        ),
        migrations.AddField(
            model_name="siteconfig",
            name="waitlist_confirmation_subject",
            field=models.CharField(
                blank=True,
                default="You’re on the Local Market NE waitlist",
                help_text="Subject for the waitlist confirmation email.",
                max_length=160,
            ),
        ),
        migrations.AddField(
            model_name="siteconfig",
            name="waitlist_confirmation_body",
            field=models.TextField(
                blank=True,
                default=(
                    "Thanks for joining the Local Market NE waitlist!\n\n"
                    "We’ll email you when we launch.\n\n"
                    "— Local Market NE"
                ),
                help_text="Body for the waitlist confirmation email (plain text).",
            ),
        ),
    ]
