# Generated by Django 5.1.15 on 2026-02-17 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_siteconfig_age_gate_text_and_more'),
        ('core', '0025_waitlistentry'),
    ]

    operations = [
    ]
