# Generated by ChatGPT on 2026-02-16
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0026_siteconfig_waitlist"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfig",
            name="support_email",
            field=models.EmailField(
                blank=True,
                default="",
                help_text="Public support email shown on Contact/Help pages (optional).",
                max_length=254,
            ),
        ),
    ]
