# Generated by Django 5.1.15 on 2026-02-17 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_merge_20260216_2002'),
        ('core', '0026_siteconfig_waitlist'),
    ]

    operations = [
    ]
