# Generated by Django 5.1.15 on 2026-02-17 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_merge_20260216_2123'),
        ('core', '0027_siteconfig_support_email'),
    ]

    operations = [
    ]
