# Generated by ChatGPT on 2026-02-16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0028_merge_20260216_2252"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfig",
            name="support_form_enabled",
            field=models.BooleanField(default=True, help_text="If enabled, the Contact form is available to the public."),
        ),
        migrations.AddField(
            model_name="siteconfig",
            name="support_store_messages",
            field=models.BooleanField(default=True, help_text="If enabled, Contact form submissions are stored in the database for staff review."),
        ),
        migrations.AddField(
            model_name="siteconfig",
            name="support_send_email",
            field=models.BooleanField(default=True, help_text="If enabled, Contact form submissions are emailed to the support address (best-effort)."),
        ),
        migrations.AddField(
            model_name="siteconfig",
            name="support_admin_notify_enabled",
            field=models.BooleanField(default=False, help_text="If enabled, notify the admin address when a new Contact message is received."),
        ),
        migrations.AddField(
            model_name="siteconfig",
            name="support_admin_email",
            field=models.EmailField(blank=True, default="", help_text="Optional admin email to notify for Contact messages (used only if admin notify is enabled).", max_length=254),
        ),
        migrations.AddField(
            model_name="siteconfig",
            name="support_auto_reply_enabled",
            field=models.BooleanField(default=False, help_text="If enabled, send a basic auto-reply to the sender confirming receipt (best-effort)."),
        ),
        migrations.AddField(
            model_name="siteconfig",
            name="support_auto_reply_subject",
            field=models.CharField(blank=True, default="We received your message", help_text="Subject for the support auto-reply email (if enabled).", max_length=160),
        ),
        migrations.AddField(
            model_name="siteconfig",
            name="support_auto_reply_body",
            field=models.TextField(blank=True, default="Thanks for reaching out to Local Market NE.\n\nWe received your message and will get back to you as soon as possible.\n\n- Local Market NE", help_text="Body for the support auto-reply email (plain text)."),
        ),
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(blank=True, default="", max_length=120)),
                ("email", models.EmailField(max_length=254)),
                ("subject", models.CharField(blank=True, default="", max_length=160)),
                ("message", models.TextField(max_length=4000)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("source_path", models.CharField(blank=True, default="", max_length=200)),
                ("user_agent", models.CharField(blank=True, default="", max_length=240)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("is_resolved", models.BooleanField(default=False)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("resolved_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="resolved_contact_messages", to=settings.AUTH_USER_MODEL)),
                ("user", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="contact_messages", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
