# Generated by ChatGPT on 2026-02-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0033_siteconfig_checkout_switch"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfig",
            name="environment_banner_enabled",
            field=models.BooleanField(
                default=False,
                help_text=(
                    "If enabled, show an environment banner sitewide (useful for staging or test mode warnings). "
                    "A test-mode Stripe key in production will also trigger an automatic warning banner."
                ),
            ),
        ),
        migrations.AddField(
            model_name="siteconfig",
            name="environment_banner_text",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Text shown in the environment banner. Keep it short.",
                max_length=240,
            ),
        ),
    ]
