# Generated by Django 5.1.15 on 2026-02-14 13:41

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LegalDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "doc_type",
                    models.CharField(
                        choices=[
                            ("terms", "Terms of Service"),
                            ("privacy", "Privacy Policy"),
                            ("refund", "Refund Policy"),
                            ("content", "Content & Safety Policy"),
                            ("seller_agreement", "Seller Agreement"),
                            ("fulfillment_policy", "Fulfillment Policy"),
                            ("services_policy", "Services & Appointments Policy"),
                            ("seller_fees", "Seller Fees"),
                        ],
                        max_length=24,
                    ),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                ("title", models.CharField(max_length=200)),
                (
                    "body",
                    models.TextField(
                        help_text="HTML is allowed. Content is rendered as trusted HTML (admin-only editing)."
                    ),
                ),
                ("is_published", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["doc_type", "-version"],
                "indexes": [
                    models.Index(
                        fields=["doc_type", "is_published", "-version"],
                        name="legal_legal_doc_typ_8a087c_idx",
                    ),
                    models.Index(
                        fields=["is_published", "-created_at"],
                        name="legal_legal_is_publ_106338_idx",
                    ),
                ],
                "unique_together": {("doc_type", "version")},
            },
        ),
        migrations.CreateModel(
            name="LegalAcceptance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "guest_email",
                    models.EmailField(blank=True, default="", max_length=254),
                ),
                (
                    "accepted_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "user_agent",
                    models.CharField(blank=True, default="", max_length=300),
                ),
                ("document_hash", models.CharField(db_index=True, max_length=64)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="legal_acceptances",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="acceptances",
                        to="legal.legaldocument",
                    ),
                ),
            ],
            options={
                "ordering": ["-accepted_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "accepted_at"],
                        name="legal_legal_user_id_76a094_idx",
                    ),
                    models.Index(
                        fields=["guest_email", "accepted_at"],
                        name="legal_legal_guest_e_547d41_idx",
                    ),
                    models.Index(
                        fields=["document", "accepted_at"],
                        name="legal_legal_documen_984bbe_idx",
                    ),
                ],
            },
        ),
    ]
