# Generated by Django 5.1.15 on 2026-02-14 13:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AnalyticsEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[("PAGEVIEW", "Pageview"), ("THROTTLE", "Throttle")],
                        default="PAGEVIEW",
                        max_length=32,
                    ),
                ),
                ("path", models.CharField(db_index=True, max_length=512)),
                ("method", models.CharField(default="GET", max_length=8)),
                ("status_code", models.PositiveIntegerField(default=200)),
                (
                    "visitor_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="Stable first-party visitor id (hc_vid cookie).",
                        max_length=36,
                    ),
                ),
                (
                    "session_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="Session id (hc_sid cookie). Rotates after inactivity window.",
                        max_length=36,
                    ),
                ),
                (
                    "session_key",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=64
                    ),
                ),
                (
                    "ip_hash",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=64
                    ),
                ),
                (
                    "host",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=255
                    ),
                ),
                (
                    "environment",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=32
                    ),
                ),
                ("is_staff", models.BooleanField(db_index=True, default=False)),
                ("is_bot", models.BooleanField(db_index=True, default=False)),
                (
                    "user_agent",
                    models.CharField(blank=True, default="", max_length=400),
                ),
                (
                    "referrer",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=512
                    ),
                ),
                ("meta", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="analytics_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["event_type", "created_at"],
                        name="analytics_a_event_t_6c35be_idx",
                    ),
                    models.Index(
                        fields=["path", "created_at"],
                        name="analytics_a_path_27a354_idx",
                    ),
                    models.Index(
                        fields=["visitor_id", "created_at"],
                        name="analytics_a_visitor_cc66fd_idx",
                    ),
                    models.Index(
                        fields=["session_id", "created_at"],
                        name="analytics_a_session_533ea7_idx",
                    ),
                    models.Index(
                        fields=["host", "created_at"],
                        name="analytics_a_host_58ad35_idx",
                    ),
                    models.Index(
                        fields=["environment", "created_at"],
                        name="analytics_a_environ_4119fc_idx",
                    ),
                ],
            },
        ),
    ]
