# Generated by Django 5.1.15 on 2026-02-16 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyticsevent',
            name='event_type',
            field=models.CharField(choices=[('PAGEVIEW', 'Pageview'), ('THROTTLE', 'Throttle'), ('ADD_TO_CART', 'Add to cart'), ('CHECKOUT_STARTED', 'Checkout started'), ('ORDER_PAID', 'Order paid')], default='PAGEVIEW', max_length=32),
        ),
    ]
