# Generated by Django 5.1.15 on 2026-02-14 13:41

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bio",
                    models.TextField(
                        blank=True, help_text="Short public bio/about for your shop."
                    ),
                ),
                (
                    "website",
                    models.URLField(blank=True, help_text="Personal or shop website."),
                ),
                (
                    "social_instagram",
                    models.URLField(blank=True, help_text="Instagram profile URL."),
                ),
                (
                    "social_twitter",
                    models.URLField(blank=True, help_text="Twitter/X profile URL."),
                ),
                (
                    "social_facebook",
                    models.URLField(blank=True, help_text="Facebook profile URL."),
                ),
                (
                    "social_youtube",
                    models.URLField(blank=True, help_text="YouTube channel URL."),
                ),
                (
                    "venmo_handle",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Optional Venmo handle (no @).",
                        max_length=64,
                    ),
                ),
                (
                    "paypal_me_url",
                    models.URLField(
                        blank=True, default="", help_text="Optional PayPal.me URL."
                    ),
                ),
                (
                    "zelle_contact",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Optional Zelle contact (email).",
                        max_length=120,
                    ),
                ),
                ("first_name", models.CharField(blank=True, max_length=150)),
                ("last_name", models.CharField(blank=True, max_length=150)),
                (
                    "shop_name",
                    models.CharField(
                        blank=True,
                        help_text="Optional public shop name. If blank, your username is shown.",
                        max_length=80,
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("email_verified", models.BooleanField(default=False)),
                (
                    "email_verification_token",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                (
                    "email_verification_sent_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "phone_1",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a valid phone number (digits and - + ( ) allowed).",
                                regex="^[0-9\\-\\+\\(\\) ]{7,20}$",
                            )
                        ],
                    ),
                ),
                (
                    "phone_2",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a valid phone number (digits and - + ( ) allowed).",
                                regex="^[0-9\\-\\+\\(\\) ]{7,20}$",
                            )
                        ],
                    ),
                ),
                ("address_1", models.CharField(blank=True, max_length=255)),
                ("address_2", models.CharField(blank=True, max_length=255)),
                ("city", models.CharField(blank=True, max_length=120)),
                (
                    "state",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("AL", "Alabama"),
                            ("AK", "Alaska"),
                            ("AZ", "Arizona"),
                            ("AR", "Arkansas"),
                            ("CA", "California"),
                            ("CO", "Colorado"),
                            ("CT", "Connecticut"),
                            ("DE", "Delaware"),
                            ("FL", "Florida"),
                            ("GA", "Georgia"),
                            ("HI", "Hawaii"),
                            ("ID", "Idaho"),
                            ("IL", "Illinois"),
                            ("IN", "Indiana"),
                            ("IA", "Iowa"),
                            ("KS", "Kansas"),
                            ("KY", "Kentucky"),
                            ("LA", "Louisiana"),
                            ("ME", "Maine"),
                            ("MD", "Maryland"),
                            ("MA", "Massachusetts"),
                            ("MI", "Michigan"),
                            ("MN", "Minnesota"),
                            ("MS", "Mississippi"),
                            ("MO", "Missouri"),
                            ("MT", "Montana"),
                            ("NE", "Nebraska"),
                            ("NV", "Nevada"),
                            ("NH", "New Hampshire"),
                            ("NJ", "New Jersey"),
                            ("NM", "New Mexico"),
                            ("NY", "New York"),
                            ("NC", "North Carolina"),
                            ("ND", "North Dakota"),
                            ("OH", "Ohio"),
                            ("OK", "Oklahoma"),
                            ("OR", "Oregon"),
                            ("PA", "Pennsylvania"),
                            ("RI", "Rhode Island"),
                            ("SC", "South Carolina"),
                            ("SD", "South Dakota"),
                            ("TN", "Tennessee"),
                            ("TX", "Texas"),
                            ("UT", "Utah"),
                            ("VT", "Vermont"),
                            ("VA", "Virginia"),
                            ("WA", "Washington"),
                            ("WV", "West Virginia"),
                            ("WI", "Wisconsin"),
                            ("WY", "Wyoming"),
                            ("DC", "District of Columbia"),
                        ],
                        max_length=2,
                    ),
                ),
                ("zip_code", models.CharField(blank=True, max_length=10)),
                (
                    "avatar",
                    models.ImageField(blank=True, null=True, upload_to="avatars/"),
                ),
                ("is_seller", models.BooleanField(default=False)),
                ("is_owner", models.BooleanField(default=False)),
                ("stripe_account_id", models.CharField(blank=True, max_length=255)),
                ("stripe_onboarding_complete", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["is_seller"], name="accounts_pr_is_sell_5dd651_idx"
                    ),
                    models.Index(
                        fields=["is_owner"], name="accounts_pr_is_owne_717a8b_idx"
                    ),
                    models.Index(
                        fields=["shop_name"], name="accounts_pr_shop_na_ca2dd3_idx"
                    ),
                ],
            },
        ),
    ]
