# Generated by ChatGPT on 2026-02-14
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="is_age_18_confirmed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="profile",
            name="age_18_confirmed_at",
            field=models.DateTimeField(null=True, blank=True),
        ),
        migrations.AddIndex(
            model_name="profile",
            index=models.Index(fields=["is_age_18_confirmed"], name="accounts_pro_is_age_1e8d51_idx"),
        ),
    ]
