# Generated by Django 5.1.15 on 2026-02-15 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_profile_age_18_confirm"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="profile",
            new_name="accounts_pr_is_age__21ff69_idx",
            old_name="accounts_pro_is_age_1e8d51_idx",
        ),
    ]
