# Generated by Django 5.1.15 on 2026-02-16 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_public_location'),
        ('accounts', '0003_rename_accounts_pro_is_age_1e8d51_idx_accounts_pr_is_age__21ff69_idx'),
    ]

    operations = [
    ]
