# Generated by Django 5.1.15 on 2026-02-16 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_merge_20260216_1016'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='profile',
            new_name='accounts_pr_public__236fc7_idx',
            old_name='accounts_pr_public__f7c5b4_idx',
        ),
    ]
