# Generated by Django 5.1.15 on 2026-02-16 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_seller_policy_ack'),
        ('accounts', '0005_rename_accounts_pr_public__f7c5b4_idx_accounts_pr_public__236fc7_idx'),
    ]

    operations = [
    ]
