# Generated by ChatGPT on 2026-03-05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_merge_20260216_1518"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="cashapp_handle",
            field=models.CharField(blank=True, default="", help_text="Optional Cash App handle (no $).", max_length=64),
        ),
        migrations.AddField(
            model_name="profile",
            name="show_cashapp_qr_checkout",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="profile",
            name="show_cashapp_qr_storefront",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="profile",
            name="show_paypal_qr_checkout",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="profile",
            name="show_paypal_qr_storefront",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="profile",
            name="show_venmo_qr_checkout",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="profile",
            name="show_venmo_qr_storefront",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="profile",
            name="show_zelle_qr_checkout",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="profile",
            name="show_zelle_qr_storefront",
            field=models.BooleanField(default=False),
        ),
    ]
