# Generated by ChatGPT on 2026-03-11

from django.core.validators import RegexValidator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_profile_offplatform_qr_settings"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="storefront_banner",
            field=models.ImageField(
                blank=True,
                help_text="Optional storefront banner image shown on your shop header.",
                null=True,
                upload_to="storefront/banners/",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="storefront_logo",
            field=models.ImageField(
                blank=True,
                help_text="Optional storefront logo shown on your shop header.",
                null=True,
                upload_to="storefront/logos/",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="storefront_primary_color",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Storefront accent color in hex (example: #2F4F2F).",
                max_length=7,
                validators=[
                    RegexValidator(
                        message="Enter a valid hex color like #2F4F2F.",
                        regex="^#[0-9A-Fa-f]{6}$",
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="storefront_theme_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Allow your storefront to use your custom branding color.",
            ),
        ),
    ]
