# Generated by ChatGPT on 2026-03-11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_profile_storefront_branding"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="storefront_layout",
            field=models.CharField(
                choices=[("balanced", "Balanced"), ("catalog", "Catalog focus"), ("minimal", "Minimal")],
                default="balanced",
                help_text="Choose a storefront layout style.",
                max_length=16,
            ),
        ),
    ]
