# Generated by Django 5.1.15 on 2026-03-11 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_profile_show_business_address_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='service_radius_miles',
            field=models.PositiveIntegerField(default=0, help_text='Service providers: service radius in miles (0 = not set).'),
        ),
    ]
