# Generated by Django 5.1.15 on 2026-03-12 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_profile_service_radius_miles'),
        ('accounts', '0011_profile_private_geo_fields'),
    ]

    operations = [
    ]
