# Generated by Django 5.1.15 on 2026-02-14 13:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductQuestionThread",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(blank=True, default="", max_length=180)),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "buyer",
                    models.ForeignKey(
                        help_text="Thread starter (buyer).",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="qa_threads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="qa_threads",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProductQuestionMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("body", models.TextField()),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="qa_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="qa_messages_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "thread",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="qa.productquestionthread",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProductQuestionReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("spam", "Spam"),
                            ("harassment", "Harassment"),
                            ("hate", "Hate"),
                            ("violence", "Violence"),
                            ("sexual", "Sexual content"),
                            ("illegal", "Illegal content"),
                            ("other", "Other"),
                        ],
                        max_length=24,
                    ),
                ),
                ("details", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[("open", "Open"), ("resolved", "Resolved")],
                        db_index=True,
                        default="open",
                        max_length=12,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="qa.productquestionmessage",
                    ),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="qa_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="qa_reports_resolved",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "-created_at"],
                        name="qa_productq_status_37a506_idx",
                    ),
                    models.Index(
                        fields=["reporter", "-created_at"],
                        name="qa_productq_reporte_53c488_idx",
                    ),
                    models.Index(
                        fields=["-created_at"], name="qa_productq_created_5d9e0c_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="productquestionthread",
            index=models.Index(
                fields=["product", "-created_at"], name="qa_productq_product_55ecab_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productquestionthread",
            index=models.Index(
                fields=["buyer", "-created_at"], name="qa_productq_buyer_i_d818c2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productquestionthread",
            index=models.Index(
                fields=["-created_at"], name="qa_productq_created_eefcd7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productquestionmessage",
            index=models.Index(
                fields=["thread", "created_at"], name="qa_productq_thread__9eba41_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productquestionmessage",
            index=models.Index(
                fields=["author", "-created_at"], name="qa_productq_author__de6132_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productquestionmessage",
            index=models.Index(
                fields=["-created_at"], name="qa_productq_created_cca0f6_idx"
            ),
        ),
    ]
