# Generated by Django 5.1.15 on 2026-03-12 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_buyerreview'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='buyerreview',
            new_name='reviews_buy_buyer_i_22a772_idx',
            old_name='reviews_buy_buyer_i_6f32d4_idx',
        ),
        migrations.RenameIndex(
            model_name='buyerreview',
            new_name='reviews_buy_seller__d5880d_idx',
            old_name='reviews_buy_seller__7dce18_idx',
        ),
        migrations.RenameIndex(
            model_name='buyerreview',
            new_name='reviews_buy_rating_e314c7_idx',
            old_name='reviews_buy_rating_93c71f_idx',
        ),
    ]
