# Generated by Django 5.1.15 on 2026-02-14 13:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("order_override", "Order override"),
                            ("seller_action", "Seller action"),
                            ("moderation", "Moderation"),
                            ("settings", "Settings"),
                            ("financial", "Financial"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=64,
                    ),
                ),
                (
                    "verb",
                    models.CharField(
                        help_text="Human-friendly verb, e.g. 'force_mark_paid'.",
                        max_length=80,
                    ),
                ),
                ("reason", models.TextField(blank=True)),
                (
                    "target_object_id",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("before_json", models.JSONField(blank=True, default=dict)),
                ("after_json", models.JSONField(blank=True, default=dict)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ops_audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target_content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["action", "created_at"],
                        name="ops_auditlo_action_f4d18a_idx",
                    ),
                    models.Index(
                        fields=["verb", "created_at"],
                        name="ops_auditlo_verb_a78659_idx",
                    ),
                ],
            },
        ),
    ]
