# Generated by Django 5.1.15 on 2026-02-16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ops", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ErrorEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("request_id", models.CharField(blank=True, db_index=True, max_length=64)),
                ("path", models.CharField(blank=True, db_index=True, max_length=500)),
                ("method", models.CharField(blank=True, max_length=12)),
                ("status_code", models.PositiveIntegerField(db_index=True, default=500)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("exception_type", models.CharField(blank=True, db_index=True, max_length=200)),
                ("message", models.TextField(blank=True)),
                ("traceback", models.TextField(blank=True)),
                ("is_resolved", models.BooleanField(db_index=True, default=False)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("resolution_notes", models.TextField(blank=True)),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ops_error_events_resolved",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ops_error_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["is_resolved", "created_at"],
                        name="ops_errorev_is_reso_9d6d64_idx",
                    ),
                    models.Index(
                        fields=["status_code", "created_at"],
                        name="ops_errorev_status__c33a9d_idx",
                    ),
                    models.Index(
                        fields=["exception_type", "created_at"],
                        name="ops_errorev_excepti_3b3c0c_idx",
                    ),
                ],
            },
        ),
    ]
