# Generated by Django 5.1.15 on 2026-02-16 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0002_errorevent'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='errorevent',
            new_name='ops_errorev_is_reso_533e5b_idx',
            old_name='ops_errorev_is_reso_9d6d64_idx',
        ),
        migrations.RenameIndex(
            model_name='errorevent',
            new_name='ops_errorev_status__c31655_idx',
            old_name='ops_errorev_status__c33a9d_idx',
        ),
        migrations.RenameIndex(
            model_name='errorevent',
            new_name='ops_errorev_excepti_08a2ed_idx',
            old_name='ops_errorev_excepti_3b3c0c_idx',
        ),
    ]
