# Generated by Django 5.1.15 on 2026-02-14 13:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0001_initial"),
        ("products", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AppointmentRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("requested_start", models.DateTimeField()),
                ("requested_end", models.DateTimeField()),
                ("scheduled_start", models.DateTimeField(blank=True, null=True)),
                ("scheduled_end", models.DateTimeField(blank=True, null=True)),
                ("scheduled_notes", models.TextField(blank=True, default="")),
                ("buyer_confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("reminder_sent_at", models.DateTimeField(blank=True, null=True)),
                ("message", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("REQUESTED", "Requested"),
                            ("DEPOSIT_PENDING", "Deposit pending"),
                            ("DEPOSIT_PAID", "Deposit paid"),
                            (
                                "AWAITING_BUYER_CONFIRMATION",
                                "Awaiting buyer confirmation",
                            ),
                            ("SCHEDULED", "Scheduled"),
                            ("DECLINED", "Declined"),
                            ("CANCELED", "Canceled"),
                            ("COMPLETED", "Completed"),
                        ],
                        default="REQUESTED",
                        max_length=30,
                    ),
                ),
                ("duration_minutes_snapshot", models.PositiveIntegerField(default=0)),
                ("deposit_cents_snapshot", models.PositiveIntegerField(default=0)),
                (
                    "cancellation_policy_snapshot",
                    models.TextField(blank=True, default=""),
                ),
                (
                    "cancellation_window_hours_snapshot",
                    models.PositiveIntegerField(default=0),
                ),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                ("deposit_paid_at", models.DateTimeField(blank=True, null=True)),
                ("scheduled_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("canceled_at", models.DateTimeField(blank=True, null=True)),
                ("declined_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "buyer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointment_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="appointments",
                        to="orders.order",
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointment_requests_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointment_requests",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["seller", "status", "created_at"],
                        name="appointment_seller__e44587_idx",
                    ),
                    models.Index(
                        fields=["buyer", "status", "created_at"],
                        name="appointment_buyer_i_1dce8f_idx",
                    ),
                    models.Index(
                        fields=["service", "status", "created_at"],
                        name="appointment_service_900fce_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="AvailabilityException",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                ("is_closed", models.BooleanField(default=False)),
                ("start_time", models.TimeField(blank=True, null=True)),
                ("end_time", models.TimeField(blank=True, null=True)),
                ("note", models.CharField(blank=True, default="", max_length=160)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="availability_exceptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
                "indexes": [
                    models.Index(
                        fields=["seller", "date"], name="appointment_seller__635e53_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("seller", "date"),
                        name="uniq_availability_exception_per_seller_date",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="AvailabilityRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "weekday",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Mon"),
                            (1, "Tue"),
                            (2, "Wed"),
                            (3, "Thu"),
                            (4, "Fri"),
                            (5, "Sat"),
                            (6, "Sun"),
                        ],
                        db_index=True,
                    ),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="availability_rules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["seller_id", "weekday", "start_time"],
                "indexes": [
                    models.Index(
                        fields=["seller", "is_active", "weekday"],
                        name="appointment_seller__ca3b77_idx",
                    )
                ],
            },
        ),
    ]
