# Generated by Django 5.1.15 on 2026-02-14 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("GOOD", "Goods"), ("SERVICE", "Services")],
                        default="GOOD",
                        max_length=10,
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("slug", models.SlugField(max_length=140)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="catalog.category",
                    ),
                ),
            ],
            options={
                "ordering": ["type", "parent_id", "name"],
            },
        ),
        migrations.CreateModel(
            name="RootCategory",
            fields=[],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("catalog.category",),
        ),
        migrations.CreateModel(
            name="SubCategory",
            fields=[],
            options={
                "verbose_name": "Subcategory",
                "verbose_name_plural": "Subcategories",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("catalog.category",),
        ),
        migrations.AddIndex(
            model_name="category",
            index=models.Index(
                fields=["type", "is_active", "sort_order"],
                name="catalog_cat_type_d24b75_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="category",
            index=models.Index(
                fields=["parent", "is_active", "sort_order"],
                name="catalog_cat_parent__a23f1f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="category",
            index=models.Index(fields=["slug"], name="catalog_cat_slug_695af4_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="category",
            unique_together={("type", "parent", "slug")},
        ),
    ]
