# Generated by ChatGPT on 2026-02-14
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="is_prohibited",
            field=models.BooleanField(
                default=False,
                help_text="If enabled, listings in this category are prohibited on the marketplace (v1).",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="requires_age_18",
            field=models.BooleanField(
                default=False,
                help_text="If enabled, buyers must confirm they are 18+ to purchase items in this category.",
            ),
        ),
        migrations.AddIndex(
            model_name="category",
            index=models.Index(fields=["is_prohibited", "requires_age_18"], name="catalog_cat_is_proh_9c1a61_idx"),
        ),
    ]
