# Generated by ChatGPT Pack Z on 2026-02-14
from __future__ import annotations

from django.db import migrations


def seed_prohibited_categories(apps, schema_editor):
    Category = apps.get_model("catalog", "Category")

    seeds = [
        # Goods only (v1 prohibits these categories entirely)
        {"type": "GOOD", "name": "Weapons", "slug": "weapons", "is_prohibited": True, "requires_age_18": True},
        {"type": "GOOD", "name": "Alcohol", "slug": "alcohol", "is_prohibited": True, "requires_age_18": True},
    ]

    for data in seeds:
        obj, created = Category.objects.get_or_create(
            type=data["type"],
            parent=None,
            slug=data["slug"],
            defaults={
                "name": data["name"],
                "description": "",
                "is_active": True,
                "sort_order": 999,
                "is_prohibited": data["is_prohibited"],
                "requires_age_18": data["requires_age_18"],
            },
        )
        # Ensure flags stay true even if the category existed.
        changed = False
        for k in ["is_prohibited", "requires_age_18"]:
            if getattr(obj, k) != data[k]:
                setattr(obj, k, data[k])
                changed = True
        if changed:
            obj.save(update_fields=["is_prohibited", "requires_age_18", "updated_at"])


def noop_reverse(apps, schema_editor):
    # Do not delete categories automatically.
    return


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0002_category_policy_flags"),
    ]

    operations = [
        migrations.RunPython(seed_prohibited_categories, noop_reverse),
    ]
