# Generated by Django 5.1.15 on 2026-02-15 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_category_policy_flags"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="category",
            new_name="catalog_cat_is_proh_9e94f0_idx",
            old_name="catalog_cat_is_proh_9c1a61_idx",
        ),
    ]
