# Generated by Django 5.1.15 on 2026-02-15 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "catalog",
            "0003_rename_catalog_cat_is_proh_9c1a61_idx_catalog_cat_is_proh_9e94f0_idx",
        ),
        ("catalog", "0003_seed_prohibited_categories"),
    ]

    operations = []
