# Generated by Django 5.1.15 on 2026-02-17 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_merge_20260214_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='type',
            field=models.CharField(choices=[('GOOD', 'Products'), ('SERVICE', 'Services')], default='GOOD', max_length=10),
        ),
    ]
