# Generated by Django 5.1.15 on 2026-02-14 13:41

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "guest_email",
                    models.EmailField(blank=True, default="", max_length=254),
                ),
                (
                    "order_token",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending", "Pending"),
                            ("awaiting_payment", "Awaiting payment"),
                            ("paid", "Paid"),
                            ("canceled", "Canceled"),
                            ("refunded", "Refunded"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=24,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("digital", "Digital only"),
                            ("physical", "Physical only"),
                            ("mixed", "Mixed (digital + physical)"),
                        ],
                        default="physical",
                        max_length=16,
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("stripe", "Stripe"),
                            ("venmo", "Venmo"),
                            ("paypal", "PayPal"),
                            ("zelle", "Zelle"),
                        ],
                        db_index=True,
                        default="stripe",
                        max_length=20,
                    ),
                ),
                ("currency", models.CharField(default="usd", max_length=8)),
                ("subtotal_cents", models.PositiveIntegerField(default=0)),
                ("tax_cents", models.PositiveIntegerField(default=0)),
                ("shipping_cents", models.PositiveIntegerField(default=0)),
                ("total_cents", models.PositiveIntegerField(default=0)),
                (
                    "marketplace_sales_percent_snapshot",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Marketplace % cut captured at order creation time.",
                        max_digits=5,
                    ),
                ),
                (
                    "platform_fee_cents_snapshot",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Legacy flat fee snapshot (NOT USED). Keep at 0.",
                    ),
                ),
                (
                    "stripe_session_id",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=255
                    ),
                ),
                (
                    "stripe_payment_intent_id",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("paid_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                (
                    "shipping_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "shipping_phone",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "shipping_line1",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "shipping_line2",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "shipping_city",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                (
                    "shipping_state",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                (
                    "shipping_postal_code",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                (
                    "shipping_country",
                    models.CharField(blank=True, default="", max_length=2),
                ),
                (
                    "inventory_reserved",
                    models.BooleanField(
                        default=False,
                        help_text="True if stock was reserved/decremented when the order was created (PENDING).",
                    ),
                ),
                (
                    "inventory_released",
                    models.BooleanField(
                        default=False,
                        help_text="True if reserved stock was released back (canceled/expired).",
                    ),
                ),
                (
                    "offplatform_note",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Optional buyer note when marking off-platform payment.",
                    ),
                ),
                ("offplatform_sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "buyer",
                    models.ForeignKey(
                        blank=True,
                        help_text="Registered buyer. Null means guest checkout.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderEvent",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("order_created", "Order created"),
                            ("checkout_started", "Checkout started"),
                            ("stripe_session_created", "Stripe_session_created"),
                            ("checkout_completed", "Checkout completed"),
                            ("paid", "Paid"),
                            ("canceled", "Canceled"),
                            ("refund_requested", "Refund requested"),
                            ("refunded", "Refunded"),
                            ("transfer_created", "Transfer created"),
                            ("note", "Note"),
                            ("warning", "Warning"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                ("message", models.TextField(blank=True, default="")),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="orders.order",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title_snapshot",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "sku_snapshot",
                    models.CharField(blank=True, default="", max_length=80),
                ),
                ("unit_price_cents_snapshot", models.PositiveIntegerField(default=0)),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("line_total_cents", models.PositiveIntegerField(default=0)),
                ("tax_cents", models.PositiveIntegerField(default=0)),
                ("marketplace_fee_cents", models.PositiveIntegerField(default=0)),
                ("seller_net_cents", models.PositiveIntegerField(default=0)),
                ("is_service", models.BooleanField(default=False)),
                (
                    "fulfillment_mode_snapshot",
                    models.CharField(default="pickup", max_length=20),
                ),
                (
                    "delivery_fee_cents_snapshot",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "shipping_fee_cents_snapshot",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "pickup_instructions_snapshot",
                    models.TextField(blank=True, default=""),
                ),
                (
                    "tracking_carrier",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                (
                    "tracking_number",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=64
                    ),
                ),
                ("tracking_url", models.URLField(blank=True, default="")),
                (
                    "fulfillment_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("ready", "Ready"),
                            ("shipped", "Shipped"),
                            ("delivered", "Delivered"),
                            ("canceled", "Canceled"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                    ),
                ),
                (
                    "lead_time_days_snapshot",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="orders.order",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="order_items",
                        to="products.product",
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sold_order_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SellerFulfillmentTask",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_done", models.BooleanField(default=False)),
                ("done_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "order_item",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fulfillment_task",
                        to="orders.orderitem",
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fulfillment_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StripeWebhookEvent",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("stripe_event_id", models.CharField(max_length=255, unique=True)),
                ("event_type", models.CharField(db_index=True, max_length=255)),
                ("livemode", models.BooleanField(default=False)),
                ("raw_json", models.JSONField(blank=True, default=dict)),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(db_index=True, default="received", max_length=32),
                ),
                ("error_message", models.TextField(blank=True, default="")),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "created_at"],
                        name="orders_stri_status_ccbeb9_idx",
                    ),
                    models.Index(
                        fields=["event_type", "created_at"],
                        name="orders_stri_event_t_8c4373_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="StripeWebhookDelivery",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "stripe_session_id",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=255
                    ),
                ),
                (
                    "delivered_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "status",
                    models.CharField(db_index=True, default="ok", max_length=32),
                ),
                ("error_message", models.TextField(blank=True, default="")),
                (
                    "order",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stripe_webhook_deliveries",
                        to="orders.order",
                    ),
                ),
                (
                    "webhook_event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliveries",
                        to="orders.stripewebhookevent",
                    ),
                ),
            ],
            options={
                "ordering": ["-delivered_at"],
            },
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["status", "created_at"], name="orders_orde_status_25e057_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["stripe_session_id"], name="orders_orde_stripe__efc29a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["payment_method"], name="orders_orde_payment_63e120_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="orderevent",
            index=models.Index(
                fields=["type", "created_at"], name="orders_orde_type_df6205_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="orderitem",
            index=models.Index(
                fields=["seller", "created_at"], name="orders_orde_seller__d8f1ea_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="orderitem",
            index=models.Index(
                fields=["fulfillment_status"], name="orders_orde_fulfill_1ba673_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sellerfulfillmenttask",
            index=models.Index(
                fields=["seller", "is_done", "created_at"],
                name="orders_sell_seller__8c37ab_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="stripewebhookdelivery",
            index=models.Index(
                fields=["stripe_session_id", "delivered_at"],
                name="orders_stri_stripe__4d5b36_idx",
            ),
        ),
    ]
