# Generated by ChatGPT (Pack AH)
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="is_tip",
            field=models.BooleanField(default=False),
        ),
    ]
