# Generated by Django 5.1.15 on 2026-02-16 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_orderevent_meta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderevent',
            name='type',
            field=models.CharField(choices=[('order_created', 'Order created'), ('checkout_started', 'Checkout started'), ('stripe_session_created', 'Stripe_session_created'), ('checkout_completed', 'Checkout completed'), ('paid', 'Paid'), ('canceled', 'Canceled'), ('refund_requested', 'Refund requested'), ('refunded', 'Refunded'), ('transfer_created', 'Transfer created'), ('transfer_reversed', 'Transfer reversed'), ('note', 'Note'), ('warning', 'Warning')], db_index=True, max_length=32),
        ),
    ]
