# Generated by Django 5.1.15 on 2026-03-05 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_orderevent_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('stripe', 'Stripe'), ('venmo', 'Venmo'), ('paypal', 'PayPal'), ('zelle', 'Zelle'), ('cashapp', 'Cash App')], db_index=True, default='stripe', max_length=20),
        ),
    ]
