# Generated by Django 5.1.15 on 2026-03-08 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_orderitem_fulfillment_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'permissions': (('can_retry_payouts', 'Can retry payout transfers'),)},
        ),
        migrations.AlterModelOptions(
            name='stripewebhookevent',
            options={'ordering': ['-created_at'], 'permissions': (('can_reprocess_webhooks', 'Can reprocess Stripe webhooks'),)},
        ),
    ]
