# Generated by Django 5.1.15 on 2026-03-09 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_order_options_alter_stripewebhookevent_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='platform_fee_cents_snapshot',
            field=models.PositiveIntegerField(default=0, help_text='Flat marketplace service fee snapshot captured at order creation time.'),
        ),
    ]
