# Generated by Django 5.1.15 on 2026-02-16 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_emaildeliveryattempt'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='emaildeliveryattempt',
            new_name='notificatio_status_3e5a4d_idx',
            old_name='notificatio_status__4c4c1a_idx',
        ),
        migrations.RenameIndex(
            model_name='emaildeliveryattempt',
            new_name='notificatio_to_emai_6947ef_idx',
            old_name='notificatio_to_emai_2b0c0f_idx',
        ),
        migrations.RenameIndex(
            model_name='emaildeliveryattempt',
            new_name='notificatio_notific_1e5539_idx',
            old_name='notificatio_notific_4f3c87_idx',
        ),
    ]
