# Generated by Django 5.1.15 on 2026-02-14 13:41

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "kind",
                    models.CharField(
                        choices=[("GOOD", "Product"), ("SERVICE", "Service")],
                        db_index=True,
                        default="GOOD",
                        max_length=10,
                    ),
                ),
                ("title", models.CharField(max_length=160)),
                ("slug", models.SlugField(blank=True, max_length=180)),
                (
                    "slug_is_manual",
                    models.BooleanField(
                        default=False,
                        help_text="If checked, slug will not auto-update when the title changes.",
                    ),
                ),
                (
                    "short_description",
                    models.CharField(blank=True, default="", max_length=280),
                ),
                ("description", models.TextField(blank=True, default="")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Full price for this product/service.",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                ("is_free", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(db_index=True, default=False)),
                ("is_featured", models.BooleanField(db_index=True, default=False)),
                ("is_trending", models.BooleanField(db_index=True, default=False)),
                (
                    "stock_qty",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Available quantity for products. Set 0 to indicate out of stock (unless made-to-order).",
                    ),
                ),
                (
                    "is_made_to_order",
                    models.BooleanField(
                        default=False,
                        help_text="If enabled, buyers can purchase even when stock is 0 and seller will fulfill later.",
                    ),
                ),
                (
                    "lead_time_days",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Estimated days to fulfill after purchase (for made-to-order items).",
                        null=True,
                    ),
                ),
                (
                    "fulfillment_pickup_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="If enabled, buyers can choose pickup for this product.",
                    ),
                ),
                (
                    "fulfillment_delivery_enabled",
                    models.BooleanField(
                        default=False,
                        help_text="If enabled, seller offers local delivery for this product.",
                    ),
                ),
                (
                    "fulfillment_shipping_enabled",
                    models.BooleanField(
                        default=False,
                        help_text="If enabled, seller is willing to ship this product (optional in v1).",
                    ),
                ),
                (
                    "pickup_instructions",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Shown to buyers after purchase when pickup is selected.",
                    ),
                ),
                (
                    "delivery_radius_miles",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="If delivery is enabled, maximum delivery radius in miles (optional).",
                        null=True,
                    ),
                ),
                (
                    "delivery_fee_cents",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="If delivery is enabled, optional delivery fee in cents.",
                    ),
                ),
                (
                    "shipping_fee_cents",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="If shipping is enabled, optional shipping fee in cents.",
                    ),
                ),
                (
                    "service_duration_minutes",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Service duration in minutes (15-minute increments).",
                        null=True,
                    ),
                ),
                (
                    "service_cancellation_policy",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Shown to buyers during booking/checkout.",
                    ),
                ),
                (
                    "service_cancellation_window_hours",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="If > 0, buyer cannot cancel within this many hours of the appointment start.",
                    ),
                ),
                (
                    "service_deposit_cents",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Optional deposit collected via Stripe at checkout (in cents). 0 disables deposits.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="products",
                        to="catalog.category",
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subcategory",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional subcategory under the main category.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="products_subcategory",
                        to="catalog.category",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProductEngagementEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("VIEW", "View"),
                            ("ADD_TO_CART", "Add to cart"),
                            ("CLICK", "Click"),
                            ("REVIEW", "Review"),
                            ("PURCHASE", "Purchase"),
                        ],
                        db_index=True,
                        max_length=24,
                    ),
                ),
                (
                    "session_key",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="Anonymous session key (used for throttling/analytics when user is not logged in).",
                        max_length=80,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("ip_hash", models.CharField(blank=True, default="", max_length=64)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="engagement_events",
                        to="products.product",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("image", models.ImageField(upload_to="products/images/")),
                ("alt_text", models.CharField(blank=True, default="", max_length=160)),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False,
                        help_text="Primary image used for cards/OG where applicable.",
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["kind", "is_active", "created_at"],
                name="products_pr_kind_2649a9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["slug"], name="products_pr_slug_3edc0c_idx"),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.UniqueConstraint(
                fields=("seller", "slug"), name="uniq_product_slug_per_seller"
            ),
        ),
        migrations.AddIndex(
            model_name="productengagementevent",
            index=models.Index(
                fields=["product", "kind", "created_at"],
                name="products_pr_product_758a40_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="productengagementevent",
            index=models.Index(
                fields=["kind", "created_at"], name="products_pr_kind_60567a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productimage",
            index=models.Index(
                fields=["product", "sort_order"], name="products_pr_product_f88290_idx"
            ),
        ),
    ]
