# Generated by Django 5.1.15 on 2026-03-09 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_savedsearchalert_email_enabled'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='savedsearchalert',
            new_name='products_sa_user_id_88139f_idx',
            old_name='products_sa_user_id_7a3dd8_idx',
        ),
        migrations.RenameIndex(
            model_name='savedsearchalert',
            new_name='products_sa_kind_52463e_idx',
            old_name='products_sa_kind_9de24b_idx',
        ),
    ]
